---
- hosts: all
  user: root
  become: true

# Variables are taken from env_variables file
  vars_files:
  - env_variables
  tasks:

 # Add a REHL subscription to machine
  - name: Add RHEL subscription
    rhsm_repository:
      name: "{{item}}"
      state: enabled
    with_items: "{{subscriptions}}"
